version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: jtemplate-mysql
    networks:
      - jtemplate
    ports: 
      - '3306:33060'
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: jtemplate-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    networks:
      - jtemplate
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - db
    container_name: jtemplate-server
    networks:
      - jtemplate
    volumes: 
      - .:/app
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_ROOT_HOST: jtemplate-mysql

volumes:
  db_data:
networks:
  jtemplate: